<?php

require_once '../init.php';


/**
 * Test class for Util.
 * Generated by PHPUnit on 2012-02-19 at 23:16:22.
 */
class UtilTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Util
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @covers Util::endsWith
     * @todo Implement testEndsWith().
     * @dataProvider provider
     */
    public function testEndsWith($str, $end, $pre) {
        $this->assertEquals($pre, Util::endsWith($str, $end));
    }

    /**
     * @covers Util::attr
     * @todo Implement testAttr().
     */
    public function testAttr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    public function provider() {
        return array(array("abc", "c", "ab"));

    }
}
?>
